nelmio_cors:
    defaults:
        allow_origin: ['*'] # Ou spécifie l'origine de ton front-end (ex : 'http://localhost:3000')
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        max_age: 3600
    paths:
        '^/': # Appliquer à toutes les routes
